"use strict";

const KEYWORDS = {
  in: {
    label: "in",
    detail: "in \"directorio\" { ... }",
    doc: "**in** define el directorio de trabajo.\n\nTodo lo que contiene (bloques `run`) se despliega relativo a esa ruta. Si el directorio no existe, Worky lo crea.\n\n**Ejemplo**\n```worky\nin \"./app\" {\n  run \"servidor\" { os: all { pnpm run dev } }\n}\n```",
  },
  run: {
    label: "run",
    detail: "run \"nombre\" { ... } | run { ... }",
    doc: "**run** crea una instancia del workspace (ventana, pestana o panel segun el modo de presentacion).\n\nEl nombre es opcional: si se omite, Worky asigna `run1`, `run2`, ...\n\nDentro admite bloques `os:` y, dentro de ellos, comandos, `set`/`export` y herramientas `/`.\n\n**Ejemplo**\n```worky\nrun \"terminal\" {\n  os: win32 { cmd }\n  os: linux { bash }\n}\n```",
  },
  os: {
    label: "os",
    detail: "os: win32 | linux | darwin | all { ... }",
    doc: "**os** ejecuta un bloque solo en el sistema indicado. Permite escribir un workspace portable entre sistemas.\n\n- `win32` - Windows\n- `linux` - Linux\n- `darwin` - macOS\n- `all` - cualquier sistema (ademas, se ejecuta despues del bloque propio)\n\n**Ejemplo**\n```worky\nrun \"shell\" {\n  os: win32 { cmd }\n  os: linux { bash }\n  os: all { echo \"listo\" }\n}\n```",
  },
  set: {
    label: "set",
    detail: "set CLAVE = valor",
    doc: "**set** define una variable de entorno de la instancia para **Windows**.\n\n**Ejemplo**\n```worky\nos: win32 {\n  set NODE_ENV = \"development\"\n}\n```",
  },
  export: {
    label: "export",
    detail: "export CLAVE = valor",
    doc: "**export** define una variable de entorno de la instancia para **Linux/macOS** (bash).\n\n**Ejemplo**\n```worky\nos: linux {\n  export NODE_ENV = \"development\"\n}\n```",
  },
};

const OS_TARGETS = [
  { label: "all", doc: "Se ejecuta en cualquier sistema operativo." },
  { label: "win32", doc: "Solo Windows." },
  { label: "linux", doc: "Solo Linux." },
  { label: "darwin", doc: "Solo macOS." },
];

const TOOLS = {
  pause: {
    label: "/pause",
    detail: "Herramienta Worky",
    doc: "**/pause** detiene la instancia hasta que el usuario pulsa Enter.\n\nUtil para dejar una ventana abierta o esperar antes de continuar.\n\n```worky\n/pause\n```",
  },
  kill: {
    label: "/kill",
    detail: "Herramienta Worky - /kill <nombre> | /kill all",
    doc: "**/kill** cierra una instancia del workspace desde otra instancia.\n\n- `/kill \"nombre\"` cierra la instancia con ese nombre.\n- `/kill all` cierra todas las instancias de la ejecucion actual.\n\n**Ejemplo**\n```worky\nrun {\n  os: all {\n    /pause\n    /kill \"servidor\"\n    /kill all\n  }\n}\n```",
  },
  shell: {
    label: "/shell",
    detail: "Herramienta Worky - /shell [comando] | /shell { ... }",
    doc: "**/shell** abre el shell del sistema (cmd en Windows, bash en Linux) de forma portable.\n\n- `/shell` abre un shell interactivo.\n- `/shell <comando>` ejecuta el comando dentro del shell y **deja el shell abierto** al terminar.\n- `/shell { ... }` ejecuta varios comandos y deja el shell abierto.\n\n**Ejemplos**\n```worky\nrun \"dev\" {\n  os: all {\n    /shell\n    /shell pnpm run dev\n    /shell {\n      git status\n      git pull\n    }\n  }\n}\n```",
  },
};

const BUILTIN_VARS = [
  { label: "$*", doc: "Todos los argumentos pasados a Worky." },
  { label: "$~1", doc: "Primer argumento posicional." },
  { label: "$~2", doc: "Segundo argumento posicional." },
];

const INTRO = {
  in: "in \"directorio\" { ... }",
  run: "run \"nombre\" { ... }",
  os: "os: win32 { ... }",
  set: "set CLAVE = valor",
  export: "export CLAVE = valor",
};

const OS_COMMANDS = {
  common: [
    ["pnpm run dev", "Ejecuta el script 'dev' del package.json con pnpm.", "pnpm"],
    ["pnpm install", "Instala las dependencias del proyecto.", "pnpm"],
    ["npm run dev", "Ejecuta el script 'dev' con npm.", "npm"],
    ["npm install", "Instala dependencias con npm.", "npm"],
    ["yarn dev", "Ejecuta el script 'dev' con Yarn.", "yarn"],
    ["git status", "Muestra el estado del repositorio.", "git"],
    ["git pull", "Trae los ultimos cambios del remoto.", "git"],
    ["docker compose up", "Levanta los servicios definidos en docker-compose.", "docker"],
    ["docker compose down", "Detiene y elimina los contenedores.", "docker"],
    ["python", "Ejecuta el interprete de Python.", "python"],
    ["python -m http.server", "Sirve el directorio actual por HTTP.", "python"],
    ["node", "Ejecuta el runtime de Node.js.", "node"],
    ["code .", "Abre el directorio actual en VS Code.", "code"],
  ],
  win32: [
    ["cmd", "Inicia una sesion de simbolo del sistema.", "shell"],
    ["powershell", "Inicia Windows PowerShell.", "shell"],
    ["pwsh", "Inicia PowerShell 7+.", "shell"],
    ["cd", "Cambia de directorio.", "nav"],
    ["cls", "Limpia la pantalla.", "screen"],
    ["dir", "Lista el contenido del directorio.", "fs"],
    ["copy", "Copia archivos.", "fs"],
    ["move", "Mueve archivos o renombra.", "fs"],
    ["del", "Elimina archivos.", "fs"],
    ["type", "Muestra el contenido de un archivo.", "fs"],
    ["find", "Busca texto dentro de archivos.", "search"],
    ["findstr", "Busca cadenas con expresiones regulares.", "search"],
    ["where", "Localiza un ejecutable en el PATH.", "search"],
    ["start", "Abre un programa o una URL.", "shell"],
    ["tasklist", "Lista los procesos en ejecucion.", "proc"],
    ["taskkill", "Termina procesos por nombre o PID.", "proc"],
    ["ping", "Comprueba conectividad de red.", "net"],
    ["ipconfig", "Muestra la configuracion de red.", "net"],
    ["netstat", "Muestra conexiones y puertos.", "net"],
    ["curl", "Transfiere datos desde o hacia una URL.", "net"],
    ["robocopy", "Copia archivos o arboles de directorios.", "fs"],
    ["xcopy", "Copia archivos y arboles de directorios.", "fs"],
    ["set", "Define o muestra variables de entorno en cmd.", "env"],
    ["chcp", "Cambia la pagina de codigos de la consola.", "screen"],
    ["echo", "Imprime texto en la consola.", "text"],
    ["mkdir", "Crea un directorio.", "fs"],
    ["rmdir", "Elimina un directorio.", "fs"],
    ["ren", "Renombra archivos o directorios.", "fs"],
    ["pause", "Espera a que el usuario pulse una tecla.", "shell"],
  ],
  linux: [
    ["bash", "Inicia una sesion de bash.", "shell"],
    ["sh", "Inicia el shell POSIX.", "shell"],
    ["zsh", "Inicia Zsh.", "shell"],
    ["cd", "Cambia de directorio.", "nav"],
    ["pwd", "Muestra el directorio actual.", "nav"],
    ["ls", "Lista el contenido del directorio.", "fs"],
    ["clear", "Limpia la pantalla.", "screen"],
    ["cp", "Copia archivos o directorios.", "fs"],
    ["mv", "Mueve o renombra.", "fs"],
    ["rm", "Elimina archivos o directorios.", "fs"],
    ["ln", "Crea enlaces simbolicos o duros.", "fs"],
    ["touch", "Crea un archivo vacio o actualiza su fecha.", "fs"],
    ["mkdir", "Crea un directorio.", "fs"],
    ["cat", "Muestra el contenido de archivos.", "text"],
    ["head", "Muestra las primeras lineas.", "text"],
    ["tail", "Muestra las ultimas lineas.", "text"],
    ["less", "Pagina el contenido de un archivo.", "text"],
    ["grep", "Busca texto con expresiones regulares.", "search"],
    ["sed", "Edita flujos de texto.", "text"],
    ["awk", "Procesa texto por columnas y patrones.", "text"],
    ["find", "Busca archivos en el arbol de directorios.", "search"],
    ["chmod", "Cambia los permisos de un archivo.", "perm"],
    ["chown", "Cambia el propietario de un archivo.", "perm"],
    ["ps", "Lista los procesos en ejecucion.", "proc"],
    ["top", "Monitor de procesos en tiempo real.", "proc"],
    ["kill", "Envia una senal a un proceso.", "proc"],
    ["df", "Muestra el uso del disco.", "disk"],
    ["du", "Muestra el uso de disco por directorio.", "disk"],
    ["free", "Muestra el uso de memoria.", "mem"],
    ["uname", "Muestra informacion del sistema.", "sys"],
    ["whoami", "Muestra el usuario actual.", "sys"],
    ["systemctl", "Gestiona servicios de systemd.", "svc"],
    ["service", "Gestiona servicios del sistema.", "svc"],
    ["apt", "Gestor de paquetes de Debian/Ubuntu.", "pkg"],
    ["apt-get", "Gestor de paquetes clasico de Debian.", "pkg"],
    ["dnf", "Gestor de paquetes de Fedora.", "pkg"],
    ["pacman", "Gestor de paquetes de Arch.", "pkg"],
    ["pip", "Gestor de paquetes de Python.", "pkg"],
    ["curl", "Transfiere datos desde o hacia una URL.", "net"],
    ["wget", "Descarga archivos de la red.", "net"],
    ["ssh", "Conexion remota segura.", "net"],
    ["rsync", "Sincroniza archivos de forma incremental.", "net"],
    ["tar", "Empaqueta o extrae archivos .tar.", "archive"],
    ["zip", "Comprime archivos.", "archive"],
    ["unzip", "Descomprime archivos .zip.", "archive"],
    ["echo", "Imprime texto en la consola.", "text"],
    ["export", "Define variables de entorno.", "env"],
    ["source", "Ejecuta un script en el shell actual.", "shell"],
    ["env", "Muestra o define variables de entorno.", "env"],
    ["history", "Muestra el historial de comandos.", "shell"],
    ["alias", "Crea alias de comandos.", "shell"],
    ["jobs", "Lista trabajos en segundo plano.", "proc"],
    ["nohup", "Ejecuta un comando inmune al cierre.", "proc"],
    ["tmux", "Multiplexor de terminal.", "term"],
    ["vim", "Editor de texto en consola.", "editor"],
    ["nano", "Editor de texto sencillo.", "editor"],
  ],
};

module.exports = {
  KEYWORDS,
  OS_TARGETS,
  TOOLS,
  BUILTIN_VARS,
  INTRO,
  OS_COMMANDS,
};
